[env]
OPENCC_INCLUDE_DIRS = { value = "OpenCC/build/include/opencc", relative = true }
OPENCC_LIB_DIRS = { value = "OpenCC/build/lib/glibc", relative = true }
OPENCC_LIBS = "opencc:marisa"
OPENCC_STATIC = "1"
OPENCC_DYLIB_STDCPP = "0"
OPENCC_STATIC_STDCPP = "1"
