name: Test build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt-get install -y mingw-w64
      - run: gcc --version
      - run: rustup target add x86_64-pc-windows-gnu
      - run: rustup target add x86_64-unknown-linux-gnu
      - run: cargo build_mingw_release
      - run: cargo build_glibc_release
